package com.ikea.entites;
// Generated Apr 12, 2021 1:23:08 AM by Hibernate Tools 5.3.6.Final


import java.math.BigDecimal;

/**
 * BdHdtcTaxLineT generated by hbm2java
 */
public class BdHdtcTaxLineT  implements java.io.Serializable {


     private BdHdtcTaxLineTId id;
     private BdHdtcLineT bdHdtcLineT;
     private String taxCodeSell;
     private BigDecimal taxRateSell;
     private String taxCodeBuy;
     private BigDecimal taxRateBuy;
     private String taxCurCode;
     private String taxType;
     private String gaCodeTax;
     private String gaTypeTax;
     private BigDecimal taxAmount;
     private BigDecimal taxAmountLoc;
     private String taxCurCodeLoc;
     private String taxTypeAbbrDef;
     private String taxTypeAbbrLoc;

    public BdHdtcTaxLineT() {
    }

	
    public BdHdtcTaxLineT(BdHdtcTaxLineTId id, BdHdtcLineT bdHdtcLineT) {
        this.id = id;
        this.bdHdtcLineT = bdHdtcLineT;
    }
    public BdHdtcTaxLineT(BdHdtcTaxLineTId id, BdHdtcLineT bdHdtcLineT, String taxCodeSell, BigDecimal taxRateSell, String taxCodeBuy, BigDecimal taxRateBuy, String taxCurCode, String taxType, String gaCodeTax, String gaTypeTax, BigDecimal taxAmount, BigDecimal taxAmountLoc, String taxCurCodeLoc, String taxTypeAbbrDef, String taxTypeAbbrLoc) {
       this.id = id;
       this.bdHdtcLineT = bdHdtcLineT;
       this.taxCodeSell = taxCodeSell;
       this.taxRateSell = taxRateSell;
       this.taxCodeBuy = taxCodeBuy;
       this.taxRateBuy = taxRateBuy;
       this.taxCurCode = taxCurCode;
       this.taxType = taxType;
       this.gaCodeTax = gaCodeTax;
       this.gaTypeTax = gaTypeTax;
       this.taxAmount = taxAmount;
       this.taxAmountLoc = taxAmountLoc;
       this.taxCurCodeLoc = taxCurCodeLoc;
       this.taxTypeAbbrDef = taxTypeAbbrDef;
       this.taxTypeAbbrLoc = taxTypeAbbrLoc;
    }
   
    public BdHdtcTaxLineTId getId() {
        return this.id;
    }
    
    public void setId(BdHdtcTaxLineTId id) {
        this.id = id;
    }
    public BdHdtcLineT getBdHdtcLineT() {
        return this.bdHdtcLineT;
    }
    
    public void setBdHdtcLineT(BdHdtcLineT bdHdtcLineT) {
        this.bdHdtcLineT = bdHdtcLineT;
    }
    public String getTaxCodeSell() {
        return this.taxCodeSell;
    }
    
    public void setTaxCodeSell(String taxCodeSell) {
        this.taxCodeSell = taxCodeSell;
    }
    public BigDecimal getTaxRateSell() {
        return this.taxRateSell;
    }
    
    public void setTaxRateSell(BigDecimal taxRateSell) {
        this.taxRateSell = taxRateSell;
    }
    public String getTaxCodeBuy() {
        return this.taxCodeBuy;
    }
    
    public void setTaxCodeBuy(String taxCodeBuy) {
        this.taxCodeBuy = taxCodeBuy;
    }
    public BigDecimal getTaxRateBuy() {
        return this.taxRateBuy;
    }
    
    public void setTaxRateBuy(BigDecimal taxRateBuy) {
        this.taxRateBuy = taxRateBuy;
    }
    public String getTaxCurCode() {
        return this.taxCurCode;
    }
    
    public void setTaxCurCode(String taxCurCode) {
        this.taxCurCode = taxCurCode;
    }
    public String getTaxType() {
        return this.taxType;
    }
    
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }
    public String getGaCodeTax() {
        return this.gaCodeTax;
    }
    
    public void setGaCodeTax(String gaCodeTax) {
        this.gaCodeTax = gaCodeTax;
    }
    public String getGaTypeTax() {
        return this.gaTypeTax;
    }
    
    public void setGaTypeTax(String gaTypeTax) {
        this.gaTypeTax = gaTypeTax;
    }
    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }
    
    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }
    public BigDecimal getTaxAmountLoc() {
        return this.taxAmountLoc;
    }
    
    public void setTaxAmountLoc(BigDecimal taxAmountLoc) {
        this.taxAmountLoc = taxAmountLoc;
    }
    public String getTaxCurCodeLoc() {
        return this.taxCurCodeLoc;
    }
    
    public void setTaxCurCodeLoc(String taxCurCodeLoc) {
        this.taxCurCodeLoc = taxCurCodeLoc;
    }
    public String getTaxTypeAbbrDef() {
        return this.taxTypeAbbrDef;
    }
    
    public void setTaxTypeAbbrDef(String taxTypeAbbrDef) {
        this.taxTypeAbbrDef = taxTypeAbbrDef;
    }
    public String getTaxTypeAbbrLoc() {
        return this.taxTypeAbbrLoc;
    }
    
    public void setTaxTypeAbbrLoc(String taxTypeAbbrLoc) {
        this.taxTypeAbbrLoc = taxTypeAbbrLoc;
    }




}


