package com.ikea.entites;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BdHdtcLineTId generated by hbm2java
 */
@Embeddable
public class BdHdtcLineTId implements java.io.Serializable {

    private BigDecimal bdId;
    private int lineNo;

    public BdHdtcLineTId() {
    }

    public BdHdtcLineTId(BigDecimal bdId, int lineNo) {
        this.bdId = bdId;
        this.lineNo = lineNo;
    }

    @Column(name = "BD_ID", nullable = false, scale = 0)
    public BigDecimal getBdId() {
        return this.bdId;
    }

    public void setBdId(BigDecimal bdId) {
        this.bdId = bdId;
    }

    @Column(name = "LINE_NO", nullable = false, precision = 9, scale = 0)
    public int getLineNo() {
        return this.lineNo;
    }

    public void setLineNo(int lineNo) {
        this.lineNo = lineNo;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof BdHdtcLineTId))
            return false;
        BdHdtcLineTId castOther = (BdHdtcLineTId) other;

        return ((this.getBdId() == castOther.getBdId()) || (this.getBdId() != null && castOther.getBdId() != null
                && this.getBdId().equals(castOther.getBdId()))) && (this.getLineNo() == castOther.getLineNo());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getBdId() == null ? 0 : this.getBdId().hashCode());
        result = 37 * result + this.getLineNo();
        return result;
    }

}
