package com.ikea.entites;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BdHdtcTaxLineTId generated by hbm2java
 */
@Embeddable
public class BdHdtcTaxLineTId implements java.io.Serializable {

    private BigDecimal bdId;
    private int lineNo;
    private int lineTaxNo;

    public BdHdtcTaxLineTId() {
    }

    public BdHdtcTaxLineTId(BigDecimal bdId, int lineNo, int lineTaxNo) {
        this.bdId = bdId;
        this.lineNo = lineNo;
        this.lineTaxNo = lineTaxNo;
    }

    @Column(name = "BD_ID", nullable = false, scale = 0)
    public BigDecimal getBdId() {
        return this.bdId;
    }

    public void setBdId(BigDecimal bdId) {
        this.bdId = bdId;
    }

    @Column(name = "LINE_NO", nullable = false, precision = 9, scale = 0)
    public int getLineNo() {
        return this.lineNo;
    }

    public void setLineNo(int lineNo) {
        this.lineNo = lineNo;
    }

    @Column(name = "LINE_TAX_NO", nullable = false, precision = 9, scale = 0)
    public int getLineTaxNo() {
        return this.lineTaxNo;
    }

    public void setLineTaxNo(int lineTaxNo) {
        this.lineTaxNo = lineTaxNo;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof BdHdtcTaxLineTId))
            return false;
        BdHdtcTaxLineTId castOther = (BdHdtcTaxLineTId) other;

        return ((this.getBdId() == castOther.getBdId()) || (this.getBdId() != null && castOther.getBdId() != null
                && this.getBdId().equals(castOther.getBdId()))) && (this.getLineNo() == castOther.getLineNo())
                && (this.getLineTaxNo() == castOther.getLineTaxNo());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getBdId() == null ? 0 : this.getBdId().hashCode());
        result = 37 * result + this.getLineNo();
        result = 37 * result + this.getLineTaxNo();
        return result;
    }

}
