package com.ikea.entites;
// Generated Apr 12, 2021 1:23:08 AM by Hibernate Tools 5.3.6.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BdLineComponT generated by hbm2java
 */
public class BdLineComponT  implements java.io.Serializable {


     private BdLineComponTId id;
     private BdLineT bdLineT;
     private BigDecimal bdlcPri;
     private BigDecimal bdlcAmount;
     private String bdlcCurCode;
     private BigDecimal bdlcValNet;
     private Date updDate;
     private Integer optLockVersNo;
     private String billingCode;
     private String calcMode;
     private BigDecimal bdlcPriOrig;
     private BigDecimal bdlcAmountOrig;
     private String bdlcCurCodeOrig;
     private Boolean manPriFlag;
     private String valType;
     private String costMapRef;
     private BigDecimal priFetchRpyId;
     private Set bdLineComponTaxTs = new HashSet(0);

    public BdLineComponT() {
    }

	
    public BdLineComponT(BdLineComponTId id, BdLineT bdLineT) {
        this.id = id;
        this.bdLineT = bdLineT;
    }
    public BdLineComponT(BdLineComponTId id, BdLineT bdLineT, BigDecimal bdlcPri, BigDecimal bdlcAmount, String bdlcCurCode, BigDecimal bdlcValNet, Date updDate, Integer optLockVersNo, String billingCode, String calcMode, BigDecimal bdlcPriOrig, BigDecimal bdlcAmountOrig, String bdlcCurCodeOrig, Boolean manPriFlag, String valType, String costMapRef, BigDecimal priFetchRpyId, Set bdLineComponTaxTs) {
       this.id = id;
       this.bdLineT = bdLineT;
       this.bdlcPri = bdlcPri;
       this.bdlcAmount = bdlcAmount;
       this.bdlcCurCode = bdlcCurCode;
       this.bdlcValNet = bdlcValNet;
       this.updDate = updDate;
       this.optLockVersNo = optLockVersNo;
       this.billingCode = billingCode;
       this.calcMode = calcMode;
       this.bdlcPriOrig = bdlcPriOrig;
       this.bdlcAmountOrig = bdlcAmountOrig;
       this.bdlcCurCodeOrig = bdlcCurCodeOrig;
       this.manPriFlag = manPriFlag;
       this.valType = valType;
       this.costMapRef = costMapRef;
       this.priFetchRpyId = priFetchRpyId;
       this.bdLineComponTaxTs = bdLineComponTaxTs;
    }
   
    public BdLineComponTId getId() {
        return this.id;
    }
    
    public void setId(BdLineComponTId id) {
        this.id = id;
    }
    public BdLineT getBdLineT() {
        return this.bdLineT;
    }
    
    public void setBdLineT(BdLineT bdLineT) {
        this.bdLineT = bdLineT;
    }
    public BigDecimal getBdlcPri() {
        return this.bdlcPri;
    }
    
    public void setBdlcPri(BigDecimal bdlcPri) {
        this.bdlcPri = bdlcPri;
    }
    public BigDecimal getBdlcAmount() {
        return this.bdlcAmount;
    }
    
    public void setBdlcAmount(BigDecimal bdlcAmount) {
        this.bdlcAmount = bdlcAmount;
    }
    public String getBdlcCurCode() {
        return this.bdlcCurCode;
    }
    
    public void setBdlcCurCode(String bdlcCurCode) {
        this.bdlcCurCode = bdlcCurCode;
    }
    public BigDecimal getBdlcValNet() {
        return this.bdlcValNet;
    }
    
    public void setBdlcValNet(BigDecimal bdlcValNet) {
        this.bdlcValNet = bdlcValNet;
    }
    public Date getUpdDate() {
        return this.updDate;
    }
    
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
    public Integer getOptLockVersNo() {
        return this.optLockVersNo;
    }
    
    public void setOptLockVersNo(Integer optLockVersNo) {
        this.optLockVersNo = optLockVersNo;
    }
    public String getBillingCode() {
        return this.billingCode;
    }
    
    public void setBillingCode(String billingCode) {
        this.billingCode = billingCode;
    }
    public String getCalcMode() {
        return this.calcMode;
    }
    
    public void setCalcMode(String calcMode) {
        this.calcMode = calcMode;
    }
    public BigDecimal getBdlcPriOrig() {
        return this.bdlcPriOrig;
    }
    
    public void setBdlcPriOrig(BigDecimal bdlcPriOrig) {
        this.bdlcPriOrig = bdlcPriOrig;
    }
    public BigDecimal getBdlcAmountOrig() {
        return this.bdlcAmountOrig;
    }
    
    public void setBdlcAmountOrig(BigDecimal bdlcAmountOrig) {
        this.bdlcAmountOrig = bdlcAmountOrig;
    }
    public String getBdlcCurCodeOrig() {
        return this.bdlcCurCodeOrig;
    }
    
    public void setBdlcCurCodeOrig(String bdlcCurCodeOrig) {
        this.bdlcCurCodeOrig = bdlcCurCodeOrig;
    }
    public Boolean getManPriFlag() {
        return this.manPriFlag;
    }
    
    public void setManPriFlag(Boolean manPriFlag) {
        this.manPriFlag = manPriFlag;
    }
    public String getValType() {
        return this.valType;
    }
    
    public void setValType(String valType) {
        this.valType = valType;
    }
    public String getCostMapRef() {
        return this.costMapRef;
    }
    
    public void setCostMapRef(String costMapRef) {
        this.costMapRef = costMapRef;
    }
    public BigDecimal getPriFetchRpyId() {
        return this.priFetchRpyId;
    }
    
    public void setPriFetchRpyId(BigDecimal priFetchRpyId) {
        this.priFetchRpyId = priFetchRpyId;
    }
    public Set getBdLineComponTaxTs() {
        return this.bdLineComponTaxTs;
    }
    
    public void setBdLineComponTaxTs(Set bdLineComponTaxTs) {
        this.bdLineComponTaxTs = bdLineComponTaxTs;
    }




}


