package com.ikea.entites;
// Generated Apr 12, 2021 1:23:08 AM by Hibernate Tools 5.3.6.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BdLineT generated by hbm2java
 */
public class BdLineT  implements java.io.Serializable {


     private BdLineTId id;
     private BdT bdT;
     private BigDecimal bdBuIdCnor;
     private BigDecimal bdBuIdCnee;
     private String buCodeSup;
     private String buTypeSup;
     private String supCtyOfOrig;
     private String supCtyOfOrigNameDef;
     private String supCtyOfOrigNameLoc;
     private String itemId;
     private String itemType;
     private String itemNameDef;
     private String itemNameLoc;
     private BigDecimal itemQty;
     private BigDecimal itemWeiNet;
     private BigDecimal itemWeiGro;
     private BigDecimal itemVolNet;
     private BigDecimal itemVolGro;
     private String measUnitNo;
     private String measNameDef;
     private String measNameLoc;
     private String tarNoImp;
     private String tarNoExp;
     private String statisNo;
     private Integer colli;
     private Boolean bondedFlag;
     private Date updDate;
     private Integer optLockVersNo;
     private String distrType;
     private Integer bdlNoRefBasis;
     private String prodAreaNo;
     private BigDecimal bdIdRefBasis;
     private BigDecimal subNetAmount;
     private BigDecimal subTaxAmount1;
     private BigDecimal subGroAmount1;
     private BigDecimal subTaxAmount2;
     private BigDecimal subGroAmount2;
     private BigDecimal itemQty17;
     private BigDecimal itemQty28;
     private String uomItemQtyDisp;
     private String uomItemWeiGro;
     private String uomItemWeiNet;
     private String uomItemVolGro;
     private String uomItemVolNet;
     private BigDecimal sumItemWeiGro;
     private BigDecimal sumItemWeiNet;
     private BigDecimal sumItemVolGro;
     private BigDecimal sumItemVolNet;
     private Boolean calcWeiVolFlag;
     private String lineSrcKey1;
     private String lineSrcKey2;
     private String lineSrcKey3;
     private String lineSrcKey4;
     private String lineSrcKey5;
     private Set bdLineComponTs = new HashSet(0);

    public BdLineT() {
    }


    public BdLineT(BdLineTId id, BdT bdT) {
        this.id = id;
        this.bdT = bdT;
    }
    public BdLineT(BdLineTId id, BdT bdT, BigDecimal bdBuIdCnor, BigDecimal bdBuIdCnee, String buCodeSup, String buTypeSup, String supCtyOfOrig, String supCtyOfOrigNameDef, String supCtyOfOrigNameLoc, String itemId, String itemType, String itemNameDef, String itemNameLoc, BigDecimal itemQty, BigDecimal itemWeiNet, BigDecimal itemWeiGro, BigDecimal itemVolNet, BigDecimal itemVolGro, String measUnitNo, String measNameDef, String measNameLoc, String tarNoImp, String tarNoExp, String statisNo, Integer colli, Boolean bondedFlag, Date updDate, Integer optLockVersNo, String distrType, Integer bdlNoRefBasis, String prodAreaNo, BigDecimal bdIdRefBasis, BigDecimal subNetAmount, BigDecimal subTaxAmount1, BigDecimal subGroAmount1, BigDecimal subTaxAmount2, BigDecimal subGroAmount2, BigDecimal itemQty17, BigDecimal itemQty28, String uomItemQtyDisp, String uomItemWeiGro, String uomItemWeiNet, String uomItemVolGro, String uomItemVolNet, BigDecimal sumItemWeiGro, BigDecimal sumItemWeiNet, BigDecimal sumItemVolGro, BigDecimal sumItemVolNet, Boolean calcWeiVolFlag, String lineSrcKey1, String lineSrcKey2, String lineSrcKey3, String lineSrcKey4, String lineSrcKey5, Set bdLineComponTs) {
       this.id = id;
       this.bdT = bdT;
       this.bdBuIdCnor = bdBuIdCnor;
       this.bdBuIdCnee = bdBuIdCnee;
       this.buCodeSup = buCodeSup;
       this.buTypeSup = buTypeSup;
       this.supCtyOfOrig = supCtyOfOrig;
       this.supCtyOfOrigNameDef = supCtyOfOrigNameDef;
       this.supCtyOfOrigNameLoc = supCtyOfOrigNameLoc;
       this.itemId = itemId;
       this.itemType = itemType;
       this.itemNameDef = itemNameDef;
       this.itemNameLoc = itemNameLoc;
       this.itemQty = itemQty;
       this.itemWeiNet = itemWeiNet;
       this.itemWeiGro = itemWeiGro;
       this.itemVolNet = itemVolNet;
       this.itemVolGro = itemVolGro;
       this.measUnitNo = measUnitNo;
       this.measNameDef = measNameDef;
       this.measNameLoc = measNameLoc;
       this.tarNoImp = tarNoImp;
       this.tarNoExp = tarNoExp;
       this.statisNo = statisNo;
       this.colli = colli;
       this.bondedFlag = bondedFlag;
       this.updDate = updDate;
       this.optLockVersNo = optLockVersNo;
       this.distrType = distrType;
       this.bdlNoRefBasis = bdlNoRefBasis;
       this.prodAreaNo = prodAreaNo;
       this.bdIdRefBasis = bdIdRefBasis;
       this.subNetAmount = subNetAmount;
       this.subTaxAmount1 = subTaxAmount1;
       this.subGroAmount1 = subGroAmount1;
       this.subTaxAmount2 = subTaxAmount2;
       this.subGroAmount2 = subGroAmount2;
       this.itemQty17 = itemQty17;
       this.itemQty28 = itemQty28;
       this.uomItemQtyDisp = uomItemQtyDisp;
       this.uomItemWeiGro = uomItemWeiGro;
       this.uomItemWeiNet = uomItemWeiNet;
       this.uomItemVolGro = uomItemVolGro;
       this.uomItemVolNet = uomItemVolNet;
       this.sumItemWeiGro = sumItemWeiGro;
       this.sumItemWeiNet = sumItemWeiNet;
       this.sumItemVolGro = sumItemVolGro;
       this.sumItemVolNet = sumItemVolNet;
       this.calcWeiVolFlag = calcWeiVolFlag;
       this.lineSrcKey1 = lineSrcKey1;
       this.lineSrcKey2 = lineSrcKey2;
       this.lineSrcKey3 = lineSrcKey3;
       this.lineSrcKey4 = lineSrcKey4;
       this.lineSrcKey5 = lineSrcKey5;
       this.bdLineComponTs = bdLineComponTs;
    }

    public BdLineTId getId() {
        return this.id;
    }

    public void setId(BdLineTId id) {
        this.id = id;
    }
    public BdT getBdT() {
        return this.bdT;
    }

    public void setBdT(BdT bdT) {
        this.bdT = bdT;
    }
    public BigDecimal getBdBuIdCnor() {
        return this.bdBuIdCnor;
    }

    public void setBdBuIdCnor(BigDecimal bdBuIdCnor) {
        this.bdBuIdCnor = bdBuIdCnor;
    }
    public BigDecimal getBdBuIdCnee() {
        return this.bdBuIdCnee;
    }

    public void setBdBuIdCnee(BigDecimal bdBuIdCnee) {
        this.bdBuIdCnee = bdBuIdCnee;
    }
    public String getBuCodeSup() {
        return this.buCodeSup;
    }

    public void setBuCodeSup(String buCodeSup) {
        this.buCodeSup = buCodeSup;
    }
    public String getBuTypeSup() {
        return this.buTypeSup;
    }

    public void setBuTypeSup(String buTypeSup) {
        this.buTypeSup = buTypeSup;
    }
    public String getSupCtyOfOrig() {
        return this.supCtyOfOrig;
    }

    public void setSupCtyOfOrig(String supCtyOfOrig) {
        this.supCtyOfOrig = supCtyOfOrig;
    }
    public String getSupCtyOfOrigNameDef() {
        return this.supCtyOfOrigNameDef;
    }

    public void setSupCtyOfOrigNameDef(String supCtyOfOrigNameDef) {
        this.supCtyOfOrigNameDef = supCtyOfOrigNameDef;
    }
    public String getSupCtyOfOrigNameLoc() {
        return this.supCtyOfOrigNameLoc;
    }

    public void setSupCtyOfOrigNameLoc(String supCtyOfOrigNameLoc) {
        this.supCtyOfOrigNameLoc = supCtyOfOrigNameLoc;
    }
    public String getItemId() {
        return this.itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }
    public String getItemType() {
        return this.itemType;
    }

    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
    public String getItemNameDef() {
        return this.itemNameDef;
    }

    public void setItemNameDef(String itemNameDef) {
        this.itemNameDef = itemNameDef;
    }
    public String getItemNameLoc() {
        return this.itemNameLoc;
    }

    public void setItemNameLoc(String itemNameLoc) {
        this.itemNameLoc = itemNameLoc;
    }
    public BigDecimal getItemQty() {
        return this.itemQty;
    }

    public void setItemQty(BigDecimal itemQty) {
        this.itemQty = itemQty;
    }
    public BigDecimal getItemWeiNet() {
        return this.itemWeiNet;
    }

    public void setItemWeiNet(BigDecimal itemWeiNet) {
        this.itemWeiNet = itemWeiNet;
    }
    public BigDecimal getItemWeiGro() {
        return this.itemWeiGro;
    }

    public void setItemWeiGro(BigDecimal itemWeiGro) {
        this.itemWeiGro = itemWeiGro;
    }
    public BigDecimal getItemVolNet() {
        return this.itemVolNet;
    }

    public void setItemVolNet(BigDecimal itemVolNet) {
        this.itemVolNet = itemVolNet;
    }
    public BigDecimal getItemVolGro() {
        return this.itemVolGro;
    }

    public void setItemVolGro(BigDecimal itemVolGro) {
        this.itemVolGro = itemVolGro;
    }
    public String getMeasUnitNo() {
        return this.measUnitNo;
    }

    public void setMeasUnitNo(String measUnitNo) {
        this.measUnitNo = measUnitNo;
    }
    public String getMeasNameDef() {
        return this.measNameDef;
    }

    public void setMeasNameDef(String measNameDef) {
        this.measNameDef = measNameDef;
    }
    public String getMeasNameLoc() {
        return this.measNameLoc;
    }

    public void setMeasNameLoc(String measNameLoc) {
        this.measNameLoc = measNameLoc;
    }
    public String getTarNoImp() {
        return this.tarNoImp;
    }

    public void setTarNoImp(String tarNoImp) {
        this.tarNoImp = tarNoImp;
    }
    public String getTarNoExp() {
        return this.tarNoExp;
    }

    public void setTarNoExp(String tarNoExp) {
        this.tarNoExp = tarNoExp;
    }
    public String getStatisNo() {
        return this.statisNo;
    }

    public void setStatisNo(String statisNo) {
        this.statisNo = statisNo;
    }
    public Integer getColli() {
        return this.colli;
    }

    public void setColli(Integer colli) {
        this.colli = colli;
    }
    public Boolean getBondedFlag() {
        return this.bondedFlag;
    }

    public void setBondedFlag(Boolean bondedFlag) {
        this.bondedFlag = bondedFlag;
    }
    public Date getUpdDate() {
        return this.updDate;
    }

    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
    public Integer getOptLockVersNo() {
        return this.optLockVersNo;
    }

    public void setOptLockVersNo(Integer optLockVersNo) {
        this.optLockVersNo = optLockVersNo;
    }
    public String getDistrType() {
        return this.distrType;
    }

    public void setDistrType(String distrType) {
        this.distrType = distrType;
    }
    public Integer getBdlNoRefBasis() {
        return this.bdlNoRefBasis;
    }

    public void setBdlNoRefBasis(Integer bdlNoRefBasis) {
        this.bdlNoRefBasis = bdlNoRefBasis;
    }
    public String getProdAreaNo() {
        return this.prodAreaNo;
    }

    public void setProdAreaNo(String prodAreaNo) {
        this.prodAreaNo = prodAreaNo;
    }
    public BigDecimal getBdIdRefBasis() {
        return this.bdIdRefBasis;
    }

    public void setBdIdRefBasis(BigDecimal bdIdRefBasis) {
        this.bdIdRefBasis = bdIdRefBasis;
    }
    public BigDecimal getSubNetAmount() {
        return this.subNetAmount;
    }

    public void setSubNetAmount(BigDecimal subNetAmount) {
        this.subNetAmount = subNetAmount;
    }
    public BigDecimal getSubTaxAmount1() {
        return this.subTaxAmount1;
    }

    public void setSubTaxAmount1(BigDecimal subTaxAmount1) {
        this.subTaxAmount1 = subTaxAmount1;
    }
    public BigDecimal getSubGroAmount1() {
        return this.subGroAmount1;
    }

    public void setSubGroAmount1(BigDecimal subGroAmount1) {
        this.subGroAmount1 = subGroAmount1;
    }
    public BigDecimal getSubTaxAmount2() {
        return this.subTaxAmount2;
    }

    public void setSubTaxAmount2(BigDecimal subTaxAmount2) {
        this.subTaxAmount2 = subTaxAmount2;
    }
    public BigDecimal getSubGroAmount2() {
        return this.subGroAmount2;
    }

    public void setSubGroAmount2(BigDecimal subGroAmount2) {
        this.subGroAmount2 = subGroAmount2;
    }
    public BigDecimal getItemQty17() {
        return this.itemQty17;
    }

    public void setItemQty17(BigDecimal itemQty17) {
        this.itemQty17 = itemQty17;
    }
    public BigDecimal getItemQty28() {
        return this.itemQty28;
    }

    public void setItemQty28(BigDecimal itemQty28) {
        this.itemQty28 = itemQty28;
    }
    public String getUomItemQtyDisp() {
        return this.uomItemQtyDisp;
    }

    public void setUomItemQtyDisp(String uomItemQtyDisp) {
        this.uomItemQtyDisp = uomItemQtyDisp;
    }
    public String getUomItemWeiGro() {
        return this.uomItemWeiGro;
    }

    public void setUomItemWeiGro(String uomItemWeiGro) {
        this.uomItemWeiGro = uomItemWeiGro;
    }
    public String getUomItemWeiNet() {
        return this.uomItemWeiNet;
    }

    public void setUomItemWeiNet(String uomItemWeiNet) {
        this.uomItemWeiNet = uomItemWeiNet;
    }
    public String getUomItemVolGro() {
        return this.uomItemVolGro;
    }

    public void setUomItemVolGro(String uomItemVolGro) {
        this.uomItemVolGro = uomItemVolGro;
    }
    public String getUomItemVolNet() {
        return this.uomItemVolNet;
    }

    public void setUomItemVolNet(String uomItemVolNet) {
        this.uomItemVolNet = uomItemVolNet;
    }
    public BigDecimal getSumItemWeiGro() {
        return this.sumItemWeiGro;
    }

    public void setSumItemWeiGro(BigDecimal sumItemWeiGro) {
        this.sumItemWeiGro = sumItemWeiGro;
    }
    public BigDecimal getSumItemWeiNet() {
        return this.sumItemWeiNet;
    }

    public void setSumItemWeiNet(BigDecimal sumItemWeiNet) {
        this.sumItemWeiNet = sumItemWeiNet;
    }
    public BigDecimal getSumItemVolGro() {
        return this.sumItemVolGro;
    }

    public void setSumItemVolGro(BigDecimal sumItemVolGro) {
        this.sumItemVolGro = sumItemVolGro;
    }
    public BigDecimal getSumItemVolNet() {
        return this.sumItemVolNet;
    }

    public void setSumItemVolNet(BigDecimal sumItemVolNet) {
        this.sumItemVolNet = sumItemVolNet;
    }
    public Boolean getCalcWeiVolFlag() {
        return this.calcWeiVolFlag;
    }

    public void setCalcWeiVolFlag(Boolean calcWeiVolFlag) {
        this.calcWeiVolFlag = calcWeiVolFlag;
    }
    public String getLineSrcKey1() {
        return this.lineSrcKey1;
    }

    public void setLineSrcKey1(String lineSrcKey1) {
        this.lineSrcKey1 = lineSrcKey1;
    }
    public String getLineSrcKey2() {
        return this.lineSrcKey2;
    }

    public void setLineSrcKey2(String lineSrcKey2) {
        this.lineSrcKey2 = lineSrcKey2;
    }
    public String getLineSrcKey3() {
        return this.lineSrcKey3;
    }

    public void setLineSrcKey3(String lineSrcKey3) {
        this.lineSrcKey3 = lineSrcKey3;
    }
    public String getLineSrcKey4() {
        return this.lineSrcKey4;
    }

    public void setLineSrcKey4(String lineSrcKey4) {
        this.lineSrcKey4 = lineSrcKey4;
    }
    public String getLineSrcKey5() {
        return this.lineSrcKey5;
    }

    public void setLineSrcKey5(String lineSrcKey5) {
        this.lineSrcKey5 = lineSrcKey5;
    }
    public Set getBdLineComponTs() {
        return this.bdLineComponTs;
    }

    public void setBdLineComponTs(Set bdLineComponTs) {
        this.bdLineComponTs = bdLineComponTs;
    }




}


