package com.ikea.entites;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BdLineComponTId generated by hbm2java
 */
@Embeddable
class BdLineComponTId implements java.io.Serializable {

    private BigDecimal bdId;
    private int bdlNo;
    private int bdlcNo;

    public BdLineComponTId() {
    }

    public BdLineComponTId(BigDecimal bdId, int bdlNo, int bdlcNo) {
        this.bdId = bdId;
        this.bdlNo = bdlNo;
        this.bdlcNo = bdlcNo;
    }

    @Column(name = "BD_ID", nullable = false, scale = 0)
    public BigDecimal getBdId() {
        return this.bdId;
    }

    public void setBdId(BigDecimal bdId) {
        this.bdId = bdId;
    }

    @Column(name = "BDL_NO", nullable = false, precision = 9, scale = 0)
    public int getBdlNo() {
        return this.bdlNo;
    }

    public void setBdlNo(int bdlNo) {
        this.bdlNo = bdlNo;
    }

    @Column(name = "BDLC_NO", nullable = false, precision = 9, scale = 0)
    public int getBdlcNo() {
        return this.bdlcNo;
    }

    public void setBdlcNo(int bdlcNo) {
        this.bdlcNo = bdlcNo;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof BdLineComponTId))
            return false;
        BdLineComponTId castOther = (BdLineComponTId) other;

        return ((this.getBdId() == castOther.getBdId()) || (this.getBdId() != null && castOther.getBdId() != null
                && this.getBdId().equals(castOther.getBdId()))) && (this.getBdlNo() == castOther.getBdlNo())
                && (this.getBdlcNo() == castOther.getBdlcNo());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getBdId() == null ? 0 : this.getBdId().hashCode());
        result = 37 * result + this.getBdlNo();
        result = 37 * result + this.getBdlcNo();
        return result;
    }

}
