package com.ikea.entites;
// Generated Apr 12, 2021 1:23:08 AM by Hibernate Tools 5.3.6.Final


import java.math.BigDecimal;

/**
 * BdLineComponTaxT generated by hbm2java
 */
public class BdLineComponTaxT  implements java.io.Serializable {


     private BdLineComponTaxTId id;
     private BdLineComponT bdLineComponT;
     private String taxCodeSell;
     private BigDecimal taxRateSell;
     private String taxCodeBuy;
     private BigDecimal taxRateBuy;
     private String taxCurCode;
     private String taxType;
     private String gaCodeTax;
     private String gaTypeTax;
     private Integer optLockVersNo;
     private BigDecimal taxAmount;
     private BigDecimal taxAmountOrig;
     private String taxCurCodeOrig;
     private String taxCurCodeLoc;
     private BigDecimal taxAmountLoc;
     private String taxTypeAbbrDef;
     private String taxTypeAbbrLoc;
     private String taxTypeDescDef;
     private String taxTypeDescLoc;

    public BdLineComponTaxT() {
    }

	
    public BdLineComponTaxT(BdLineComponTaxTId id, BdLineComponT bdLineComponT) {
        this.id = id;
        this.bdLineComponT = bdLineComponT;
    }
    public BdLineComponTaxT(BdLineComponTaxTId id, BdLineComponT bdLineComponT, String taxCodeSell, BigDecimal taxRateSell, String taxCodeBuy, BigDecimal taxRateBuy, String taxCurCode, String taxType, String gaCodeTax, String gaTypeTax, Integer optLockVersNo, BigDecimal taxAmount, BigDecimal taxAmountOrig, String taxCurCodeOrig, String taxCurCodeLoc, BigDecimal taxAmountLoc, String taxTypeAbbrDef, String taxTypeAbbrLoc, String taxTypeDescDef, String taxTypeDescLoc) {
       this.id = id;
       this.bdLineComponT = bdLineComponT;
       this.taxCodeSell = taxCodeSell;
       this.taxRateSell = taxRateSell;
       this.taxCodeBuy = taxCodeBuy;
       this.taxRateBuy = taxRateBuy;
       this.taxCurCode = taxCurCode;
       this.taxType = taxType;
       this.gaCodeTax = gaCodeTax;
       this.gaTypeTax = gaTypeTax;
       this.optLockVersNo = optLockVersNo;
       this.taxAmount = taxAmount;
       this.taxAmountOrig = taxAmountOrig;
       this.taxCurCodeOrig = taxCurCodeOrig;
       this.taxCurCodeLoc = taxCurCodeLoc;
       this.taxAmountLoc = taxAmountLoc;
       this.taxTypeAbbrDef = taxTypeAbbrDef;
       this.taxTypeAbbrLoc = taxTypeAbbrLoc;
       this.taxTypeDescDef = taxTypeDescDef;
       this.taxTypeDescLoc = taxTypeDescLoc;
    }
   
    public BdLineComponTaxTId getId() {
        return this.id;
    }
    
    public void setId(BdLineComponTaxTId id) {
        this.id = id;
    }
    public BdLineComponT getBdLineComponT() {
        return this.bdLineComponT;
    }
    
    public void setBdLineComponT(BdLineComponT bdLineComponT) {
        this.bdLineComponT = bdLineComponT;
    }
    public String getTaxCodeSell() {
        return this.taxCodeSell;
    }
    
    public void setTaxCodeSell(String taxCodeSell) {
        this.taxCodeSell = taxCodeSell;
    }
    public BigDecimal getTaxRateSell() {
        return this.taxRateSell;
    }
    
    public void setTaxRateSell(BigDecimal taxRateSell) {
        this.taxRateSell = taxRateSell;
    }
    public String getTaxCodeBuy() {
        return this.taxCodeBuy;
    }
    
    public void setTaxCodeBuy(String taxCodeBuy) {
        this.taxCodeBuy = taxCodeBuy;
    }
    public BigDecimal getTaxRateBuy() {
        return this.taxRateBuy;
    }
    
    public void setTaxRateBuy(BigDecimal taxRateBuy) {
        this.taxRateBuy = taxRateBuy;
    }
    public String getTaxCurCode() {
        return this.taxCurCode;
    }
    
    public void setTaxCurCode(String taxCurCode) {
        this.taxCurCode = taxCurCode;
    }
    public String getTaxType() {
        return this.taxType;
    }
    
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }
    public String getGaCodeTax() {
        return this.gaCodeTax;
    }
    
    public void setGaCodeTax(String gaCodeTax) {
        this.gaCodeTax = gaCodeTax;
    }
    public String getGaTypeTax() {
        return this.gaTypeTax;
    }
    
    public void setGaTypeTax(String gaTypeTax) {
        this.gaTypeTax = gaTypeTax;
    }
    public Integer getOptLockVersNo() {
        return this.optLockVersNo;
    }
    
    public void setOptLockVersNo(Integer optLockVersNo) {
        this.optLockVersNo = optLockVersNo;
    }
    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }
    
    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }
    public BigDecimal getTaxAmountOrig() {
        return this.taxAmountOrig;
    }
    
    public void setTaxAmountOrig(BigDecimal taxAmountOrig) {
        this.taxAmountOrig = taxAmountOrig;
    }
    public String getTaxCurCodeOrig() {
        return this.taxCurCodeOrig;
    }
    
    public void setTaxCurCodeOrig(String taxCurCodeOrig) {
        this.taxCurCodeOrig = taxCurCodeOrig;
    }
    public String getTaxCurCodeLoc() {
        return this.taxCurCodeLoc;
    }
    
    public void setTaxCurCodeLoc(String taxCurCodeLoc) {
        this.taxCurCodeLoc = taxCurCodeLoc;
    }
    public BigDecimal getTaxAmountLoc() {
        return this.taxAmountLoc;
    }
    
    public void setTaxAmountLoc(BigDecimal taxAmountLoc) {
        this.taxAmountLoc = taxAmountLoc;
    }
    public String getTaxTypeAbbrDef() {
        return this.taxTypeAbbrDef;
    }
    
    public void setTaxTypeAbbrDef(String taxTypeAbbrDef) {
        this.taxTypeAbbrDef = taxTypeAbbrDef;
    }
    public String getTaxTypeAbbrLoc() {
        return this.taxTypeAbbrLoc;
    }
    
    public void setTaxTypeAbbrLoc(String taxTypeAbbrLoc) {
        this.taxTypeAbbrLoc = taxTypeAbbrLoc;
    }
    public String getTaxTypeDescDef() {
        return this.taxTypeDescDef;
    }
    
    public void setTaxTypeDescDef(String taxTypeDescDef) {
        this.taxTypeDescDef = taxTypeDescDef;
    }
    public String getTaxTypeDescLoc() {
        return this.taxTypeDescLoc;
    }
    
    public void setTaxTypeDescLoc(String taxTypeDescLoc) {
        this.taxTypeDescLoc = taxTypeDescLoc;
    }




}


