package com.ikea.entites;
// Generated Apr 12, 2021 1:23:08 AM by Hibernate Tools 5.3.6.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdT generated by hbm2java
 */
@Entity
@Table(name = "BD_T")
public class BdT implements java.io.Serializable {

    private BigDecimal bdId;
    private BigDecimal bdNo;
    private String businessType;
    private String bdTranType;
    private String bdInputType;
    private String bdFuncType;
    private String buCodeFs;
    private String buTypeFs;
    private String cfCodeFs;
    private String cfTypeFs;
    private String buCodeLb;
    private String buTypeLb;
    private String cfCodeLb;
    private String cfTypeLb;
    private String bdStat;
    private String severity;
    private BigDecimal traderIdSell;
    private BigDecimal traderIdBuy;
    private Date bdDate;
    private Date bdCreDate;
    private Date bdAuthDate;
    private Date dispatchDate;
    private Date shpStartDate;
    private String srcKey1;
    private String srcKey2;
    private String srcKey3;
    private String srcKey4;
    private String bookDocCodeSell;
    private String bookDocNoSell;
    private Date bookDateSell;
    private String bookYearPrdSell;
    private String bookDocCodeBuy;
    private String bookDocNoBuy;
    private Date bookDateBuy;
    private String bookYearPrdBuy;
    private BigDecimal invcNo;
    private BigDecimal invcVersNo;
    private Integer invcLinkNo;
    private BigDecimal bdGroupNo;
    private BigDecimal bdBuIdCnor;
    private BigDecimal bdBuIdCnee;
    private String legalBdNo;
    private String ctyCodeFs;
    private String buShortnameFs;
    private String cfShortnameFs;
    private String ctyCodeLb;
    private String buShortnameLb;
    private String cfShortnameLb;
    private String bdCreId;
    private String bdAuthId;
    private String srcNameIns;
    private BigDecimal bdIdRefFirst;
    private BigDecimal bdIdRefPrev;
    private BigDecimal bdIdRefBasis;
    private String taxIndicator;
    private String taxTxtDef;
    private String taxTxtLoc;
    private String taxCtySell;
    private String taxStateSell;
    private String taxCtyBuy;
    private String taxStateBuy;
    private BigDecimal taxReprSell;
    private BigDecimal taxReprBuy;
    private String covlRef;
    private String ctyOfOrig;
    private String luId;
    private String freeLoadingUnitId;
    private String trptDocNo;
    private String buCodeShpCre;
    private String buTypeShpCre;
    private String shpNo;
    private Boolean bondedFlag;
    private BigDecimal bdBuIdCp;
    private String delTerm;
    private String delTermCsm;
    private String delTermPlace;
    private String bdLangCodeDef;
    private String bdLangCodeLoc;
    private String bdLangCtyCodeLoc;
    private Date updDate;
    private Date dueDate;
    private Byte bdCurDecimals;
    private String bdCurCode;
    private Date curConvDate;
    private String priceSrc;
    private Boolean bdAutoUpdLockFlag;
    private String paytermTxtDef;
    private String paytermTxtLoc;
    private String prntPossibSbd;
    private String prntPossibPbd;
    private String prntPossibCid;
    private BigDecimal subtotVol;
    private BigDecimal subtotNetWei;
    private BigDecimal subtotGroWei;
    private BigDecimal subtotNetAmount;
    private BigDecimal subtotGroAmount;
    private BigDecimal subtotColli;
    private BigDecimal subtotTaxAmount;
    private BigDecimal subtotQty;
    private Boolean manNetWeiFlag;
    private Boolean manGroWeiFlag;
    private Boolean manColliFlag;
    private Boolean manVolFlag;
    private Boolean manNetVolFlag;
    private String subTotalUomGroWei;
    private String subTotalUomNetWei;
    private String subTotalUomGroVol;
    private String subTotalUomNetVol;
    private BigDecimal subTotalNetVolume;
    private String certNo;
    private Integer optLockVersNo;
    private String groupCriteria;
    private Short paytermNofDays;
    private Integer bdLinkNo;
    private String weeeRegNoSell;
    private String weeeRegNoBuy;
    private String taxIndSell;
    private String taxIndBuy;
    private Boolean taxFunctionalFlag;
    private BigDecimal bdBuIdLsc;
    private Date taxDate;
    private BigDecimal bdBuIdRgr;
    private BigDecimal bdBuAltCneeIdTim;
    private Set<BdLineT> bdLineTs = new HashSet<BdLineT>(0);
    private BdHdtcT bdHdtcT;

    public BdT() {
    }

    public BdT(BigDecimal bdId, Date bdDate) {
        this.bdId = bdId;
        this.bdDate = bdDate;
    }

    public BdT(BigDecimal bdId, BigDecimal bdNo, String businessType, String bdTranType, String bdInputType,
               String bdFuncType, String buCodeFs, String buTypeFs, String cfCodeFs, String cfTypeFs, String buCodeLb,
               String buTypeLb, String cfCodeLb, String cfTypeLb, String bdStat, String severity, BigDecimal traderIdSell,
               BigDecimal traderIdBuy, Date bdDate, Date bdCreDate, Date bdAuthDate, Date dispatchDate, Date shpStartDate,
               String srcKey1, String srcKey2, String srcKey3, String srcKey4, String bookDocCodeSell,
               String bookDocNoSell, Date bookDateSell, String bookYearPrdSell, String bookDocCodeBuy, String bookDocNoBuy,
               Date bookDateBuy, String bookYearPrdBuy, BigDecimal invcNo, BigDecimal invcVersNo, Integer invcLinkNo,
               BigDecimal bdGroupNo, BigDecimal bdBuIdCnor, BigDecimal bdBuIdCnee, String legalBdNo, String ctyCodeFs,
               String buShortnameFs, String cfShortnameFs, String ctyCodeLb, String buShortnameLb, String cfShortnameLb,
               String bdCreId, String bdAuthId, String srcNameIns, BigDecimal bdIdRefFirst, BigDecimal bdIdRefPrev,
               BigDecimal bdIdRefBasis, String taxIndicator, String taxTxtDef, String taxTxtLoc, String taxCtySell,
               String taxStateSell, String taxCtyBuy, String taxStateBuy, BigDecimal taxReprSell, BigDecimal taxReprBuy,
               String covlRef, String ctyOfOrig, String luId, String freeLoadingUnitId, String trptDocNo,
               String buCodeShpCre, String buTypeShpCre, String shpNo, Boolean bondedFlag, BigDecimal bdBuIdCp,
               String delTerm, String delTermCsm, String delTermPlace, String bdLangCodeDef, String bdLangCodeLoc,
               String bdLangCtyCodeLoc, Date updDate, Date dueDate, Byte bdCurDecimals, String bdCurCode, Date curConvDate,
               String priceSrc, Boolean bdAutoUpdLockFlag, String paytermTxtDef, String paytermTxtLoc,
               String prntPossibSbd, String prntPossibPbd, String prntPossibCid, BigDecimal subtotVol,
               BigDecimal subtotNetWei, BigDecimal subtotGroWei, BigDecimal subtotNetAmount, BigDecimal subtotGroAmount,
               BigDecimal subtotColli, BigDecimal subtotTaxAmount, BigDecimal subtotQty, Boolean manNetWeiFlag,
               Boolean manGroWeiFlag, Boolean manColliFlag, Boolean manVolFlag, Boolean manNetVolFlag,
               String subTotalUomGroWei, String subTotalUomNetWei, String subTotalUomGroVol, String subTotalUomNetVol,
               BigDecimal subTotalNetVolume, String certNo, Integer optLockVersNo, String groupCriteria,
               Short paytermNofDays, Integer bdLinkNo, String weeeRegNoSell, String weeeRegNoBuy, String taxIndSell,
               String taxIndBuy, Boolean taxFunctionalFlag, BigDecimal bdBuIdLsc, Date taxDate, BigDecimal bdBuIdRgr,
               BigDecimal bdBuAltCneeIdTim, Set<BdLineT> bdLineTs, BdHdtcT bdHdtcT) {
        this.bdId = bdId;
        this.bdNo = bdNo;
        this.businessType = businessType;
        this.bdTranType = bdTranType;
        this.bdInputType = bdInputType;
        this.bdFuncType = bdFuncType;
        this.buCodeFs = buCodeFs;
        this.buTypeFs = buTypeFs;
        this.cfCodeFs = cfCodeFs;
        this.cfTypeFs = cfTypeFs;
        this.buCodeLb = buCodeLb;
        this.buTypeLb = buTypeLb;
        this.cfCodeLb = cfCodeLb;
        this.cfTypeLb = cfTypeLb;
        this.bdStat = bdStat;
        this.severity = severity;
        this.traderIdSell = traderIdSell;
        this.traderIdBuy = traderIdBuy;
        this.bdDate = bdDate;
        this.bdCreDate = bdCreDate;
        this.bdAuthDate = bdAuthDate;
        this.dispatchDate = dispatchDate;
        this.shpStartDate = shpStartDate;
        this.srcKey1 = srcKey1;
        this.srcKey2 = srcKey2;
        this.srcKey3 = srcKey3;
        this.srcKey4 = srcKey4;
        this.bookDocCodeSell = bookDocCodeSell;
        this.bookDocNoSell = bookDocNoSell;
        this.bookDateSell = bookDateSell;
        this.bookYearPrdSell = bookYearPrdSell;
        this.bookDocCodeBuy = bookDocCodeBuy;
        this.bookDocNoBuy = bookDocNoBuy;
        this.bookDateBuy = bookDateBuy;
        this.bookYearPrdBuy = bookYearPrdBuy;
        this.invcNo = invcNo;
        this.invcVersNo = invcVersNo;
        this.invcLinkNo = invcLinkNo;
        this.bdGroupNo = bdGroupNo;
        this.bdBuIdCnor = bdBuIdCnor;
        this.bdBuIdCnee = bdBuIdCnee;
        this.legalBdNo = legalBdNo;
        this.ctyCodeFs = ctyCodeFs;
        this.buShortnameFs = buShortnameFs;
        this.cfShortnameFs = cfShortnameFs;
        this.ctyCodeLb = ctyCodeLb;
        this.buShortnameLb = buShortnameLb;
        this.cfShortnameLb = cfShortnameLb;
        this.bdCreId = bdCreId;
        this.bdAuthId = bdAuthId;
        this.srcNameIns = srcNameIns;
        this.bdIdRefFirst = bdIdRefFirst;
        this.bdIdRefPrev = bdIdRefPrev;
        this.bdIdRefBasis = bdIdRefBasis;
        this.taxIndicator = taxIndicator;
        this.taxTxtDef = taxTxtDef;
        this.taxTxtLoc = taxTxtLoc;
        this.taxCtySell = taxCtySell;
        this.taxStateSell = taxStateSell;
        this.taxCtyBuy = taxCtyBuy;
        this.taxStateBuy = taxStateBuy;
        this.taxReprSell = taxReprSell;
        this.taxReprBuy = taxReprBuy;
        this.covlRef = covlRef;
        this.ctyOfOrig = ctyOfOrig;
        this.luId = luId;
        this.freeLoadingUnitId = freeLoadingUnitId;
        this.trptDocNo = trptDocNo;
        this.buCodeShpCre = buCodeShpCre;
        this.buTypeShpCre = buTypeShpCre;
        this.shpNo = shpNo;
        this.bondedFlag = bondedFlag;
        this.bdBuIdCp = bdBuIdCp;
        this.delTerm = delTerm;
        this.delTermCsm = delTermCsm;
        this.delTermPlace = delTermPlace;
        this.bdLangCodeDef = bdLangCodeDef;
        this.bdLangCodeLoc = bdLangCodeLoc;
        this.bdLangCtyCodeLoc = bdLangCtyCodeLoc;
        this.updDate = updDate;
        this.dueDate = dueDate;
        this.bdCurDecimals = bdCurDecimals;
        this.bdCurCode = bdCurCode;
        this.curConvDate = curConvDate;
        this.priceSrc = priceSrc;
        this.bdAutoUpdLockFlag = bdAutoUpdLockFlag;
        this.paytermTxtDef = paytermTxtDef;
        this.paytermTxtLoc = paytermTxtLoc;
        this.prntPossibSbd = prntPossibSbd;
        this.prntPossibPbd = prntPossibPbd;
        this.prntPossibCid = prntPossibCid;
        this.subtotVol = subtotVol;
        this.subtotNetWei = subtotNetWei;
        this.subtotGroWei = subtotGroWei;
        this.subtotNetAmount = subtotNetAmount;
        this.subtotGroAmount = subtotGroAmount;
        this.subtotColli = subtotColli;
        this.subtotTaxAmount = subtotTaxAmount;
        this.subtotQty = subtotQty;
        this.manNetWeiFlag = manNetWeiFlag;
        this.manGroWeiFlag = manGroWeiFlag;
        this.manColliFlag = manColliFlag;
        this.manVolFlag = manVolFlag;
        this.manNetVolFlag = manNetVolFlag;
        this.subTotalUomGroWei = subTotalUomGroWei;
        this.subTotalUomNetWei = subTotalUomNetWei;
        this.subTotalUomGroVol = subTotalUomGroVol;
        this.subTotalUomNetVol = subTotalUomNetVol;
        this.subTotalNetVolume = subTotalNetVolume;
        this.certNo = certNo;
        this.optLockVersNo = optLockVersNo;
        this.groupCriteria = groupCriteria;
        this.paytermNofDays = paytermNofDays;
        this.bdLinkNo = bdLinkNo;
        this.weeeRegNoSell = weeeRegNoSell;
        this.weeeRegNoBuy = weeeRegNoBuy;
        this.taxIndSell = taxIndSell;
        this.taxIndBuy = taxIndBuy;
        this.taxFunctionalFlag = taxFunctionalFlag;
        this.bdBuIdLsc = bdBuIdLsc;
        this.taxDate = taxDate;
        this.bdBuIdRgr = bdBuIdRgr;
        this.bdBuAltCneeIdTim = bdBuAltCneeIdTim;
        this.bdLineTs = bdLineTs;
        this.bdHdtcT = bdHdtcT;
    }

    @Id

    @Column(name = "BD_ID", unique = true, nullable = false, scale = 0)
    public BigDecimal getBdId() {
        return this.bdId;
    }

    public void setBdId(BigDecimal bdId) {
        this.bdId = bdId;
    }

    @Column(name = "BD_NO", scale = 0)
    public BigDecimal getBdNo() {
        return this.bdNo;
    }

    public void setBdNo(BigDecimal bdNo) {
        this.bdNo = bdNo;
    }

    @Column(name = "BUSINESS_TYPE", length = 4)
    public String getBusinessType() {
        return this.businessType;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    @Column(name = "BD_TRAN_TYPE", length = 20)
    public String getBdTranType() {
        return this.bdTranType;
    }

    public void setBdTranType(String bdTranType) {
        this.bdTranType = bdTranType;
    }

    @Column(name = "BD_INPUT_TYPE", length = 4)
    public String getBdInputType() {
        return this.bdInputType;
    }

    public void setBdInputType(String bdInputType) {
        this.bdInputType = bdInputType;
    }

    @Column(name = "BD_FUNC_TYPE", length = 4)
    public String getBdFuncType() {
        return this.bdFuncType;
    }

    public void setBdFuncType(String bdFuncType) {
        this.bdFuncType = bdFuncType;
    }

    @Column(name = "BU_CODE_FS", length = 20)
    public String getBuCodeFs() {
        return this.buCodeFs;
    }

    public void setBuCodeFs(String buCodeFs) {
        this.buCodeFs = buCodeFs;
    }

    @Column(name = "BU_TYPE_FS", length = 12)
    public String getBuTypeFs() {
        return this.buTypeFs;
    }

    public void setBuTypeFs(String buTypeFs) {
        this.buTypeFs = buTypeFs;
    }

    @Column(name = "CF_CODE_FS", length = 20)
    public String getCfCodeFs() {
        return this.cfCodeFs;
    }

    public void setCfCodeFs(String cfCodeFs) {
        this.cfCodeFs = cfCodeFs;
    }

    @Column(name = "CF_TYPE_FS", length = 12)
    public String getCfTypeFs() {
        return this.cfTypeFs;
    }

    public void setCfTypeFs(String cfTypeFs) {
        this.cfTypeFs = cfTypeFs;
    }

    @Column(name = "BU_CODE_LB", length = 20)
    public String getBuCodeLb() {
        return this.buCodeLb;
    }

    public void setBuCodeLb(String buCodeLb) {
        this.buCodeLb = buCodeLb;
    }

    @Column(name = "BU_TYPE_LB", length = 12)
    public String getBuTypeLb() {
        return this.buTypeLb;
    }

    public void setBuTypeLb(String buTypeLb) {
        this.buTypeLb = buTypeLb;
    }

    @Column(name = "CF_CODE_LB", length = 20)
    public String getCfCodeLb() {
        return this.cfCodeLb;
    }

    public void setCfCodeLb(String cfCodeLb) {
        this.cfCodeLb = cfCodeLb;
    }

    @Column(name = "CF_TYPE_LB", length = 12)
    public String getCfTypeLb() {
        return this.cfTypeLb;
    }

    public void setCfTypeLb(String cfTypeLb) {
        this.cfTypeLb = cfTypeLb;
    }

    @Column(name = "BD_STAT", length = 80)
    public String getBdStat() {
        return this.bdStat;
    }

    public void setBdStat(String bdStat) {
        this.bdStat = bdStat;
    }

    @Column(name = "SEVERITY", length = 40)
    public String getSeverity() {
        return this.severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    @Column(name = "TRADER_ID_SELL", scale = 0)
    public BigDecimal getTraderIdSell() {
        return this.traderIdSell;
    }

    public void setTraderIdSell(BigDecimal traderIdSell) {
        this.traderIdSell = traderIdSell;
    }

    @Column(name = "TRADER_ID_BUY", scale = 0)
    public BigDecimal getTraderIdBuy() {
        return this.traderIdBuy;
    }

    public void setTraderIdBuy(BigDecimal traderIdBuy) {
        this.traderIdBuy = traderIdBuy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BD_DATE", nullable = false, length = 7)
    public Date getBdDate() {
        return this.bdDate;
    }

    public void setBdDate(Date bdDate) {
        this.bdDate = bdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BD_CRE_DATE", length = 7)
    public Date getBdCreDate() {
        return this.bdCreDate;
    }

    public void setBdCreDate(Date bdCreDate) {
        this.bdCreDate = bdCreDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BD_AUTH_DATE", length = 7)
    public Date getBdAuthDate() {
        return this.bdAuthDate;
    }

    public void setBdAuthDate(Date bdAuthDate) {
        this.bdAuthDate = bdAuthDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DISPATCH_DATE", length = 7)
    public Date getDispatchDate() {
        return this.dispatchDate;
    }

    public void setDispatchDate(Date dispatchDate) {
        this.dispatchDate = dispatchDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "SHP_START_DATE", length = 7)
    public Date getShpStartDate() {
        return this.shpStartDate;
    }

    public void setShpStartDate(Date shpStartDate) {
        this.shpStartDate = shpStartDate;
    }

    @Column(name = "SRC_KEY1", length = 200)
    public String getSrcKey1() {
        return this.srcKey1;
    }

    public void setSrcKey1(String srcKey1) {
        this.srcKey1 = srcKey1;
    }

    @Column(name = "SRC_KEY2", length = 200)
    public String getSrcKey2() {
        return this.srcKey2;
    }

    public void setSrcKey2(String srcKey2) {
        this.srcKey2 = srcKey2;
    }

    @Column(name = "SRC_KEY3", length = 200)
    public String getSrcKey3() {
        return this.srcKey3;
    }

    public void setSrcKey3(String srcKey3) {
        this.srcKey3 = srcKey3;
    }

    @Column(name = "SRC_KEY4", length = 200)
    public String getSrcKey4() {
        return this.srcKey4;
    }

    public void setSrcKey4(String srcKey4) {
        this.srcKey4 = srcKey4;
    }

    @Column(name = "BOOK_DOC_CODE_SELL", length = 48)
    public String getBookDocCodeSell() {
        return this.bookDocCodeSell;
    }

    public void setBookDocCodeSell(String bookDocCodeSell) {
        this.bookDocCodeSell = bookDocCodeSell;
    }

    @Column(name = "BOOK_DOC_NO_SELL", length = 512)
    public String getBookDocNoSell() {
        return this.bookDocNoSell;
    }

    public void setBookDocNoSell(String bookDocNoSell) {
        this.bookDocNoSell = bookDocNoSell;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BOOK_DATE_SELL", length = 7)
    public Date getBookDateSell() {
        return this.bookDateSell;
    }

    public void setBookDateSell(Date bookDateSell) {
        this.bookDateSell = bookDateSell;
    }

    @Column(name = "BOOK_YEAR_PRD_SELL", length = 24)
    public String getBookYearPrdSell() {
        return this.bookYearPrdSell;
    }

    public void setBookYearPrdSell(String bookYearPrdSell) {
        this.bookYearPrdSell = bookYearPrdSell;
    }

    @Column(name = "BOOK_DOC_CODE_BUY", length = 48)
    public String getBookDocCodeBuy() {
        return this.bookDocCodeBuy;
    }

    public void setBookDocCodeBuy(String bookDocCodeBuy) {
        this.bookDocCodeBuy = bookDocCodeBuy;
    }

    @Column(name = "BOOK_DOC_NO_BUY", length = 512)
    public String getBookDocNoBuy() {
        return this.bookDocNoBuy;
    }

    public void setBookDocNoBuy(String bookDocNoBuy) {
        this.bookDocNoBuy = bookDocNoBuy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BOOK_DATE_BUY", length = 7)
    public Date getBookDateBuy() {
        return this.bookDateBuy;
    }

    public void setBookDateBuy(Date bookDateBuy) {
        this.bookDateBuy = bookDateBuy;
    }

    @Column(name = "BOOK_YEAR_PRD_BUY", length = 24)
    public String getBookYearPrdBuy() {
        return this.bookYearPrdBuy;
    }

    public void setBookYearPrdBuy(String bookYearPrdBuy) {
        this.bookYearPrdBuy = bookYearPrdBuy;
    }

    @Column(name = "INVC_NO", scale = 0)
    public BigDecimal getInvcNo() {
        return this.invcNo;
    }

    public void setInvcNo(BigDecimal invcNo) {
        this.invcNo = invcNo;
    }

    @Column(name = "INVC_VERS_NO", scale = 0)
    public BigDecimal getInvcVersNo() {
        return this.invcVersNo;
    }

    public void setInvcVersNo(BigDecimal invcVersNo) {
        this.invcVersNo = invcVersNo;
    }

    @Column(name = "INVC_LINK_NO", precision = 5, scale = 0)
    public Integer getInvcLinkNo() {
        return this.invcLinkNo;
    }

    public void setInvcLinkNo(Integer invcLinkNo) {
        this.invcLinkNo = invcLinkNo;
    }

    @Column(name = "BD_GROUP_NO", scale = 0)
    public BigDecimal getBdGroupNo() {
        return this.bdGroupNo;
    }

    public void setBdGroupNo(BigDecimal bdGroupNo) {
        this.bdGroupNo = bdGroupNo;
    }

    @Column(name = "BD_BU_ID_CNOR", scale = 0)
    public BigDecimal getBdBuIdCnor() {
        return this.bdBuIdCnor;
    }

    public void setBdBuIdCnor(BigDecimal bdBuIdCnor) {
        this.bdBuIdCnor = bdBuIdCnor;
    }

    @Column(name = "BD_BU_ID_CNEE", scale = 0)
    public BigDecimal getBdBuIdCnee() {
        return this.bdBuIdCnee;
    }

    public void setBdBuIdCnee(BigDecimal bdBuIdCnee) {
        this.bdBuIdCnee = bdBuIdCnee;
    }

    @Column(name = "LEGAL_BD_NO", length = 120)
    public String getLegalBdNo() {
        return this.legalBdNo;
    }

    public void setLegalBdNo(String legalBdNo) {
        this.legalBdNo = legalBdNo;
    }

    @Column(name = "CTY_CODE_FS", length = 40)
    public String getCtyCodeFs() {
        return this.ctyCodeFs;
    }

    public void setCtyCodeFs(String ctyCodeFs) {
        this.ctyCodeFs = ctyCodeFs;
    }

    @Column(name = "BU_SHORTNAME_FS", length = 360)
    public String getBuShortnameFs() {
        return this.buShortnameFs;
    }

    public void setBuShortnameFs(String buShortnameFs) {
        this.buShortnameFs = buShortnameFs;
    }

    @Column(name = "CF_SHORTNAME_FS", length = 360)
    public String getCfShortnameFs() {
        return this.cfShortnameFs;
    }

    public void setCfShortnameFs(String cfShortnameFs) {
        this.cfShortnameFs = cfShortnameFs;
    }

    @Column(name = "CTY_CODE_LB", length = 40)
    public String getCtyCodeLb() {
        return this.ctyCodeLb;
    }

    public void setCtyCodeLb(String ctyCodeLb) {
        this.ctyCodeLb = ctyCodeLb;
    }

    @Column(name = "BU_SHORTNAME_LB", length = 360)
    public String getBuShortnameLb() {
        return this.buShortnameLb;
    }

    public void setBuShortnameLb(String buShortnameLb) {
        this.buShortnameLb = buShortnameLb;
    }

    @Column(name = "CF_SHORTNAME_LB", length = 360)
    public String getCfShortnameLb() {
        return this.cfShortnameLb;
    }

    public void setCfShortnameLb(String cfShortnameLb) {
        this.cfShortnameLb = cfShortnameLb;
    }

    @Column(name = "BD_CRE_ID", length = 256)
    public String getBdCreId() {
        return this.bdCreId;
    }

    public void setBdCreId(String bdCreId) {
        this.bdCreId = bdCreId;
    }

    @Column(name = "BD_AUTH_ID", length = 256)
    public String getBdAuthId() {
        return this.bdAuthId;
    }

    public void setBdAuthId(String bdAuthId) {
        this.bdAuthId = bdAuthId;
    }

    @Column(name = "SRC_NAME_INS", length = 80)
    public String getSrcNameIns() {
        return this.srcNameIns;
    }

    public void setSrcNameIns(String srcNameIns) {
        this.srcNameIns = srcNameIns;
    }

    @Column(name = "BD_ID_REF_FIRST", scale = 0)
    public BigDecimal getBdIdRefFirst() {
        return this.bdIdRefFirst;
    }

    public void setBdIdRefFirst(BigDecimal bdIdRefFirst) {
        this.bdIdRefFirst = bdIdRefFirst;
    }

    @Column(name = "BD_ID_REF_PREV", scale = 0)
    public BigDecimal getBdIdRefPrev() {
        return this.bdIdRefPrev;
    }

    public void setBdIdRefPrev(BigDecimal bdIdRefPrev) {
        this.bdIdRefPrev = bdIdRefPrev;
    }

    @Column(name = "BD_ID_REF_BASIS", scale = 0)
    public BigDecimal getBdIdRefBasis() {
        return this.bdIdRefBasis;
    }

    public void setBdIdRefBasis(BigDecimal bdIdRefBasis) {
        this.bdIdRefBasis = bdIdRefBasis;
    }

    @Column(name = "TAX_INDICATOR", length = 120)
    public String getTaxIndicator() {
        return this.taxIndicator;
    }

    public void setTaxIndicator(String taxIndicator) {
        this.taxIndicator = taxIndicator;
    }

    @Column(name = "TAX_TXT_DEF", length = 560)
    public String getTaxTxtDef() {
        return this.taxTxtDef;
    }

    public void setTaxTxtDef(String taxTxtDef) {
        this.taxTxtDef = taxTxtDef;
    }

    @Column(name = "TAX_TXT_LOC", length = 4000)
    public String getTaxTxtLoc() {
        return this.taxTxtLoc;
    }

    public void setTaxTxtLoc(String taxTxtLoc) {
        this.taxTxtLoc = taxTxtLoc;
    }

    @Column(name = "TAX_CTY_SELL", length = 40)
    public String getTaxCtySell() {
        return this.taxCtySell;
    }

    public void setTaxCtySell(String taxCtySell) {
        this.taxCtySell = taxCtySell;
    }

    @Column(name = "TAX_STATE_SELL", length = 40)
    public String getTaxStateSell() {
        return this.taxStateSell;
    }

    public void setTaxStateSell(String taxStateSell) {
        this.taxStateSell = taxStateSell;
    }

    @Column(name = "TAX_CTY_BUY", length = 40)
    public String getTaxCtyBuy() {
        return this.taxCtyBuy;
    }

    public void setTaxCtyBuy(String taxCtyBuy) {
        this.taxCtyBuy = taxCtyBuy;
    }

    @Column(name = "TAX_STATE_BUY", length = 40)
    public String getTaxStateBuy() {
        return this.taxStateBuy;
    }

    public void setTaxStateBuy(String taxStateBuy) {
        this.taxStateBuy = taxStateBuy;
    }

    @Column(name = "TAX_REPR_SELL", scale = 0)
    public BigDecimal getTaxReprSell() {
        return this.taxReprSell;
    }

    public void setTaxReprSell(BigDecimal taxReprSell) {
        this.taxReprSell = taxReprSell;
    }

    @Column(name = "TAX_REPR_BUY", scale = 0)
    public BigDecimal getTaxReprBuy() {
        return this.taxReprBuy;
    }

    public void setTaxReprBuy(BigDecimal taxReprBuy) {
        this.taxReprBuy = taxReprBuy;
    }

    @Column(name = "COVL_REF", length = 88)
    public String getCovlRef() {
        return this.covlRef;
    }

    public void setCovlRef(String covlRef) {
        this.covlRef = covlRef;
    }

    @Column(name = "CTY_OF_ORIG", length = 40)
    public String getCtyOfOrig() {
        return this.ctyOfOrig;
    }

    public void setCtyOfOrig(String ctyOfOrig) {
        this.ctyOfOrig = ctyOfOrig;
    }

    @Column(name = "LU_ID", length = 160)
    public String getLuId() {
        return this.luId;
    }

    public void setLuId(String luId) {
        this.luId = luId;
    }

    @Column(name = "FREE_LOADING_UNIT_ID", length = 160)
    public String getFreeLoadingUnitId() {
        return this.freeLoadingUnitId;
    }

    public void setFreeLoadingUnitId(String freeLoadingUnitId) {
        this.freeLoadingUnitId = freeLoadingUnitId;
    }

    @Column(name = "TRPT_DOC_NO", length = 160)
    public String getTrptDocNo() {
        return this.trptDocNo;
    }

    public void setTrptDocNo(String trptDocNo) {
        this.trptDocNo = trptDocNo;
    }

    @Column(name = "BU_CODE_SHP_CRE", length = 20)
    public String getBuCodeShpCre() {
        return this.buCodeShpCre;
    }

    public void setBuCodeShpCre(String buCodeShpCre) {
        this.buCodeShpCre = buCodeShpCre;
    }

    @Column(name = "BU_TYPE_SHP_CRE", length = 12)
    public String getBuTypeShpCre() {
        return this.buTypeShpCre;
    }

    public void setBuTypeShpCre(String buTypeShpCre) {
        this.buTypeShpCre = buTypeShpCre;
    }

    @Column(name = "SHP_NO", length = 48)
    public String getShpNo() {
        return this.shpNo;
    }

    public void setShpNo(String shpNo) {
        this.shpNo = shpNo;
    }

    @Column(name = "BONDED_FLAG", precision = 1, scale = 0)
    public Boolean getBondedFlag() {
        return this.bondedFlag;
    }

    public void setBondedFlag(Boolean bondedFlag) {
        this.bondedFlag = bondedFlag;
    }

    @Column(name = "BD_BU_ID_CP", scale = 0)
    public BigDecimal getBdBuIdCp() {
        return this.bdBuIdCp;
    }

    public void setBdBuIdCp(BigDecimal bdBuIdCp) {
        this.bdBuIdCp = bdBuIdCp;
    }

    @Column(name = "DEL_TERM", length = 20)
    public String getDelTerm() {
        return this.delTerm;
    }

    public void setDelTerm(String delTerm) {
        this.delTerm = delTerm;
    }

    @Column(name = "DEL_TERM_CSM", length = 20)
    public String getDelTermCsm() {
        return this.delTermCsm;
    }

    public void setDelTermCsm(String delTermCsm) {
        this.delTermCsm = delTermCsm;
    }

    @Column(name = "DEL_TERM_PLACE", length = 280)
    public String getDelTermPlace() {
        return this.delTermPlace;
    }

    public void setDelTermPlace(String delTermPlace) {
        this.delTermPlace = delTermPlace;
    }

    @Column(name = "BD_LANG_CODE_DEF", length = 12)
    public String getBdLangCodeDef() {
        return this.bdLangCodeDef;
    }

    public void setBdLangCodeDef(String bdLangCodeDef) {
        this.bdLangCodeDef = bdLangCodeDef;
    }

    @Column(name = "BD_LANG_CODE_LOC", length = 20)
    public String getBdLangCodeLoc() {
        return this.bdLangCodeLoc;
    }

    public void setBdLangCodeLoc(String bdLangCodeLoc) {
        this.bdLangCodeLoc = bdLangCodeLoc;
    }

    @Column(name = "BD_LANG_CTY_CODE_LOC", length = 40)
    public String getBdLangCtyCodeLoc() {
        return this.bdLangCtyCodeLoc;
    }

    public void setBdLangCtyCodeLoc(String bdLangCtyCodeLoc) {
        this.bdLangCtyCodeLoc = bdLangCtyCodeLoc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "UPD_DATE", length = 7)
    public Date getUpdDate() {
        return this.updDate;
    }

    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DUE_DATE", length = 7)
    public Date getDueDate() {
        return this.dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    @Column(name = "BD_CUR_DECIMALS", precision = 2, scale = 0)
    public Byte getBdCurDecimals() {
        return this.bdCurDecimals;
    }

    public void setBdCurDecimals(Byte bdCurDecimals) {
        this.bdCurDecimals = bdCurDecimals;
    }

    @Column(name = "BD_CUR_CODE", length = 12)
    public String getBdCurCode() {
        return this.bdCurCode;
    }

    public void setBdCurCode(String bdCurCode) {
        this.bdCurCode = bdCurCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CUR_CONV_DATE", length = 7)
    public Date getCurConvDate() {
        return this.curConvDate;
    }

    public void setCurConvDate(Date curConvDate) {
        this.curConvDate = curConvDate;
    }

    @Column(name = "PRICE_SRC", length = 40)
    public String getPriceSrc() {
        return this.priceSrc;
    }

    public void setPriceSrc(String priceSrc) {
        this.priceSrc = priceSrc;
    }

    @Column(name = "BD_AUTO_UPD_LOCK_FLAG", precision = 1, scale = 0)
    public Boolean getBdAutoUpdLockFlag() {
        return this.bdAutoUpdLockFlag;
    }

    public void setBdAutoUpdLockFlag(Boolean bdAutoUpdLockFlag) {
        this.bdAutoUpdLockFlag = bdAutoUpdLockFlag;
    }

    @Column(name = "PAYTERM_TXT_DEF", length = 320)
    public String getPaytermTxtDef() {
        return this.paytermTxtDef;
    }

    public void setPaytermTxtDef(String paytermTxtDef) {
        this.paytermTxtDef = paytermTxtDef;
    }

    @Column(name = "PAYTERM_TXT_LOC", length = 4000)
    public String getPaytermTxtLoc() {
        return this.paytermTxtLoc;
    }

    public void setPaytermTxtLoc(String paytermTxtLoc) {
        this.paytermTxtLoc = paytermTxtLoc;
    }

    @Column(name = "PRNT_POSSIB_SBD", length = 40)
    public String getPrntPossibSbd() {
        return this.prntPossibSbd;
    }

    public void setPrntPossibSbd(String prntPossibSbd) {
        this.prntPossibSbd = prntPossibSbd;
    }

    @Column(name = "PRNT_POSSIB_PBD", length = 40)
    public String getPrntPossibPbd() {
        return this.prntPossibPbd;
    }

    public void setPrntPossibPbd(String prntPossibPbd) {
        this.prntPossibPbd = prntPossibPbd;
    }

    @Column(name = "PRNT_POSSIB_CID", length = 40)
    public String getPrntPossibCid() {
        return this.prntPossibCid;
    }

    public void setPrntPossibCid(String prntPossibCid) {
        this.prntPossibCid = prntPossibCid;
    }

    @Column(name = "SUBTOT_VOL", precision = 30, scale = 10)
    public BigDecimal getSubtotVol() {
        return this.subtotVol;
    }

    public void setSubtotVol(BigDecimal subtotVol) {
        this.subtotVol = subtotVol;
    }

    @Column(name = "SUBTOT_NET_WEI", precision = 30, scale = 10)
    public BigDecimal getSubtotNetWei() {
        return this.subtotNetWei;
    }

    public void setSubtotNetWei(BigDecimal subtotNetWei) {
        this.subtotNetWei = subtotNetWei;
    }

    @Column(name = "SUBTOT_GRO_WEI", precision = 30, scale = 10)
    public BigDecimal getSubtotGroWei() {
        return this.subtotGroWei;
    }

    public void setSubtotGroWei(BigDecimal subtotGroWei) {
        this.subtotGroWei = subtotGroWei;
    }

    @Column(name = "SUBTOT_NET_AMOUNT", precision = 30, scale = 10)
    public BigDecimal getSubtotNetAmount() {
        return this.subtotNetAmount;
    }

    public void setSubtotNetAmount(BigDecimal subtotNetAmount) {
        this.subtotNetAmount = subtotNetAmount;
    }

    @Column(name = "SUBTOT_GRO_AMOUNT", precision = 30, scale = 10)
    public BigDecimal getSubtotGroAmount() {
        return this.subtotGroAmount;
    }

    public void setSubtotGroAmount(BigDecimal subtotGroAmount) {
        this.subtotGroAmount = subtotGroAmount;
    }

    @Column(name = "SUBTOT_COLLI", precision = 30, scale = 10)
    public BigDecimal getSubtotColli() {
        return this.subtotColli;
    }

    public void setSubtotColli(BigDecimal subtotColli) {
        this.subtotColli = subtotColli;
    }

    @Column(name = "SUBTOT_TAX_AMOUNT", precision = 30, scale = 10)
    public BigDecimal getSubtotTaxAmount() {
        return this.subtotTaxAmount;
    }

    public void setSubtotTaxAmount(BigDecimal subtotTaxAmount) {
        this.subtotTaxAmount = subtotTaxAmount;
    }

    @Column(name = "SUBTOT_QTY", precision = 30, scale = 10)
    public BigDecimal getSubtotQty() {
        return this.subtotQty;
    }

    public void setSubtotQty(BigDecimal subtotQty) {
        this.subtotQty = subtotQty;
    }

    @Column(name = "MAN_NET_WEI_FLAG", precision = 1, scale = 0)
    public Boolean getManNetWeiFlag() {
        return this.manNetWeiFlag;
    }

    public void setManNetWeiFlag(Boolean manNetWeiFlag) {
        this.manNetWeiFlag = manNetWeiFlag;
    }

    @Column(name = "MAN_GRO_WEI_FLAG", precision = 1, scale = 0)
    public Boolean getManGroWeiFlag() {
        return this.manGroWeiFlag;
    }

    public void setManGroWeiFlag(Boolean manGroWeiFlag) {
        this.manGroWeiFlag = manGroWeiFlag;
    }

    @Column(name = "MAN_COLLI_FLAG", precision = 1, scale = 0)
    public Boolean getManColliFlag() {
        return this.manColliFlag;
    }

    public void setManColliFlag(Boolean manColliFlag) {
        this.manColliFlag = manColliFlag;
    }

    @Column(name = "MAN_VOL_FLAG", precision = 1, scale = 0)
    public Boolean getManVolFlag() {
        return this.manVolFlag;
    }

    public void setManVolFlag(Boolean manVolFlag) {
        this.manVolFlag = manVolFlag;
    }

    @Column(name = "MAN_NET_VOL_FLAG", precision = 1, scale = 0)
    public Boolean getManNetVolFlag() {
        return this.manNetVolFlag;
    }

    public void setManNetVolFlag(Boolean manNetVolFlag) {
        this.manNetVolFlag = manNetVolFlag;
    }

    @Column(name = "SUB_TOTAL_UOM_GRO_WEI", length = 80)
    public String getSubTotalUomGroWei() {
        return this.subTotalUomGroWei;
    }

    public void setSubTotalUomGroWei(String subTotalUomGroWei) {
        this.subTotalUomGroWei = subTotalUomGroWei;
    }

    @Column(name = "SUB_TOTAL_UOM_NET_WEI", length = 80)
    public String getSubTotalUomNetWei() {
        return this.subTotalUomNetWei;
    }

    public void setSubTotalUomNetWei(String subTotalUomNetWei) {
        this.subTotalUomNetWei = subTotalUomNetWei;
    }

    @Column(name = "SUB_TOTAL_UOM_GRO_VOL", length = 80)
    public String getSubTotalUomGroVol() {
        return this.subTotalUomGroVol;
    }

    public void setSubTotalUomGroVol(String subTotalUomGroVol) {
        this.subTotalUomGroVol = subTotalUomGroVol;
    }

    @Column(name = "SUB_TOTAL_UOM_NET_VOL", length = 80)
    public String getSubTotalUomNetVol() {
        return this.subTotalUomNetVol;
    }

    public void setSubTotalUomNetVol(String subTotalUomNetVol) {
        this.subTotalUomNetVol = subTotalUomNetVol;
    }

    @Column(name = "SUB_TOTAL_NET_VOLUME", precision = 30, scale = 10)
    public BigDecimal getSubTotalNetVolume() {
        return this.subTotalNetVolume;
    }

    public void setSubTotalNetVolume(BigDecimal subTotalNetVolume) {
        this.subTotalNetVolume = subTotalNetVolume;
    }

    @Column(name = "CERT_NO", length = 160)
    public String getCertNo() {
        return this.certNo;
    }

    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    @Column(name = "OPT_LOCK_VERS_NO", precision = 9, scale = 0)
    public Integer getOptLockVersNo() {
        return this.optLockVersNo;
    }

    public void setOptLockVersNo(Integer optLockVersNo) {
        this.optLockVersNo = optLockVersNo;
    }

    @Column(name = "GROUP_CRITERIA", length = 80)
    public String getGroupCriteria() {
        return this.groupCriteria;
    }

    public void setGroupCriteria(String groupCriteria) {
        this.groupCriteria = groupCriteria;
    }

    @Column(name = "PAYTERM_NOF_DAYS", precision = 3, scale = 0)
    public Short getPaytermNofDays() {
        return this.paytermNofDays;
    }

    public void setPaytermNofDays(Short paytermNofDays) {
        this.paytermNofDays = paytermNofDays;
    }

    @Column(name = "BD_LINK_NO", precision = 5, scale = 0)
    public Integer getBdLinkNo() {
        return this.bdLinkNo;
    }

    public void setBdLinkNo(Integer bdLinkNo) {
        this.bdLinkNo = bdLinkNo;
    }

    @Column(name = "WEEE_REG_NO_SELL", length = 120)
    public String getWeeeRegNoSell() {
        return this.weeeRegNoSell;
    }

    public void setWeeeRegNoSell(String weeeRegNoSell) {
        this.weeeRegNoSell = weeeRegNoSell;
    }

    @Column(name = "WEEE_REG_NO_BUY", length = 120)
    public String getWeeeRegNoBuy() {
        return this.weeeRegNoBuy;
    }

    public void setWeeeRegNoBuy(String weeeRegNoBuy) {
        this.weeeRegNoBuy = weeeRegNoBuy;
    }

    @Column(name = "TAX_IND_SELL", length = 120)
    public String getTaxIndSell() {
        return this.taxIndSell;
    }

    public void setTaxIndSell(String taxIndSell) {
        this.taxIndSell = taxIndSell;
    }

    @Column(name = "TAX_IND_BUY", length = 120)
    public String getTaxIndBuy() {
        return this.taxIndBuy;
    }

    public void setTaxIndBuy(String taxIndBuy) {
        this.taxIndBuy = taxIndBuy;
    }

    @Column(name = "TAX_FUNCTIONAL_FLAG", precision = 1, scale = 0)
    public Boolean getTaxFunctionalFlag() {
        return this.taxFunctionalFlag;
    }

    public void setTaxFunctionalFlag(Boolean taxFunctionalFlag) {
        this.taxFunctionalFlag = taxFunctionalFlag;
    }

    @Column(name = "BD_BU_ID_LSC", scale = 0)
    public BigDecimal getBdBuIdLsc() {
        return this.bdBuIdLsc;
    }

    public void setBdBuIdLsc(BigDecimal bdBuIdLsc) {
        this.bdBuIdLsc = bdBuIdLsc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "TAX_DATE", length = 7)
    public Date getTaxDate() {
        return this.taxDate;
    }

    public void setTaxDate(Date taxDate) {
        this.taxDate = taxDate;
    }

    @Column(name = "BD_BU_ID_RGR", scale = 0)
    public BigDecimal getBdBuIdRgr() {
        return this.bdBuIdRgr;
    }

    public void setBdBuIdRgr(BigDecimal bdBuIdRgr) {
        this.bdBuIdRgr = bdBuIdRgr;
    }

    @Column(name = "BD_BU_ALT_CNEE_ID_TIM", scale = 0)
    public BigDecimal getBdBuAltCneeIdTim() {
        return this.bdBuAltCneeIdTim;
    }

    public void setBdBuAltCneeIdTim(BigDecimal bdBuAltCneeIdTim) {
        this.bdBuAltCneeIdTim = bdBuAltCneeIdTim;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bdT")
    public Set<BdLineT> getBdLineTs() {
        return this.bdLineTs;
    }

    public void setBdLineTs(Set<BdLineT> bdLineTs) {
        this.bdLineTs = bdLineTs;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "bdT")
    public BdHdtcT getBdHdtcT() {
        return this.bdHdtcT;
    }

    public void setBdHdtcT(BdHdtcT bdHdtcT) {
        this.bdHdtcT = bdHdtcT;
    }

}


